In [1]:
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', 100)

In [6]:
df = pd.read_table(r'C:\Users\ChaceHawkins\OneDrive - Human Coalition\Documents\Code learning\Portfolio projects\Birds\Code\ebd_Spring_2023.txt',
                   header='infer',
                   delimiter='\t',
                   low_memory=False)

In [7]:
df.head()

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,OBSERVATION COUNT,BREEDING CODE,BREEDING CATEGORY,BEHAVIOR CODE,AGE/SEX,COUNTRY,COUNTRY CODE,STATE,STATE CODE,COUNTY,COUNTY CODE,IBA CODE,BCR CODE,USFWS CODE,ATLAS BLOCK,LOCALITY,LOCALITY ID,LOCALITY TYPE,LATITUDE,LONGITUDE,OBSERVATION DATE,TIME OBSERVATIONS STARTED,OBSERVER ID,SAMPLING EVENT IDENTIFIER,PROTOCOL TYPE,PROTOCOL CODE,PROJECT CODE,DURATION MINUTES,EFFORT DISTANCE KM,EFFORT AREA HA,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,TRIP COMMENTS,SPECIES COMMENTS,Unnamed: 49
0,URN:CornellLabOfOrnithology:EBIRD:OBS1660480746,2023-03-20 08:05:25.592778,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,United States,US,North Carolina,US-NC,Alamance,US-NC-001,NaN,29.0,NaN,NaN,Amick Rd./Guilford County Farm (ALAMANCE Co.),L10407006,H,36.13327,-79.52901,2023-03-19,10:09:00,obsr681847,S131360613,Traveling,P22,EBIRD,90.0,3.251,NaN,2.0,1,G9852368,0,1,0,NaN,NaN,NaN,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS1663467331,2023-03-23 21:07:03.315772,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,United States,US,North Carolina,US-NC,Alamance,US-NC-001,NaN,29.0,NaN,NaN,Amick Rd./Guilford County Farm (ALAMANCE Co.),L10407006,H,36.13327,-79.52901,2023-03-19,13:22:00,obsr3549973,S131644809,Traveling,P22,EBIRD,48.0,1.535,NaN,6.0,1,G9850223,0,1,0,NaN,NaN,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1663466655,2023-03-23 21:08:12.437355,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,United States,US,North Carolina,US-NC,Alamance,US-NC-001,NaN,29.0,NaN,NaN,Amick Rd./Guilford County Farm (ALAMANCE Co.),L10407006,H,36.13327,-79.52901,2023-03-19,13:22:00,obsr3647449,S131644858,Traveling,P22,EBIRD,48.0,1.535,NaN,6.0,1,G9850223,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS1665708081,2023-03-26 12:21:15.565825,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,United States,US,North Carolina,US-NC,Alamance,US-NC-001,NaN,29.0,NaN,NaN,Amick Rd./Guilford County Farm (ALAMANCE Co.),L10407006,H,36.13327,-79.52901,2023-03-26,07:51:00,obsr692156,S131853040,Traveling,P22,EBIRD,135.0,3.456,NaN,2.0,1,G9883533,0,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1665711357,2023-03-26 12:21:15.565825,21168,species,avibase-69544B59,American Crow,Corvus brachyrhynchos,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,United States,US,North Carolina,US-NC,Alamance,US-NC-001,NaN,29.0,NaN,NaN,Amick Rd./Guilford County Farm (ALAMANCE Co.),L10407006,H,36.13327,-79.52901,2023-03-26,07:51:00,obsr230061,S131853041,Traveling,P22,EBIRD,135.0,3.456,NaN,2.0,1,G9883533,0,1,0,NaN,NaN,NaN,NaN

In [8]:
df.shape

(1380924, 50)

In [10]:
df.columns

Index(['GLOBAL UNIQUE IDENTIFIER', 'LAST EDITED DATE', 'TAXONOMIC ORDER',
       'CATEGORY', 'TAXON CONCEPT ID', 'COMMON NAME', 'SCIENTIFIC NAME',
       'SUBSPECIES COMMON NAME', 'SUBSPECIES SCIENTIFIC NAME', 'EXOTIC CODE',
       'OBSERVATION COUNT', 'BREEDING CODE', 'BREEDING CATEGORY',
       'BEHAVIOR CODE', 'AGE/SEX', 'COUNTRY', 'COUNTRY CODE', 'STATE',
       'STATE CODE', 'COUNTY', 'COUNTY CODE', 'IBA CODE', 'BCR CODE',
       'USFWS CODE', 'ATLAS BLOCK', 'LOCALITY', 'LOCALITY ID', 'LOCALITY TYPE',
       'LATITUDE', 'LONGITUDE', 'OBSERVATION DATE',
       'TIME OBSERVATIONS STARTED', 'OBSERVER ID', 'SAMPLING EVENT IDENTIFIER',
       'PROTOCOL TYPE', 'PROTOCOL CODE', 'PROJECT CODE', 'DURATION MINUTES',
       'EFFORT DISTANCE KM', 'EFFORT AREA HA', 'NUMBER OBSERVERS',
       'ALL SPECIES REPORTED', 'GROUP IDENTIFIER', 'HAS MEDIA', 'APPROVED',
       'REVIEWED', 'REASON', 'TRIP COMMENTS', 'SPECIES COMMENTS',
       'Unnamed: 49'],
      dtype='object')

In [11]:
df.isnull().sum()

GLOBAL UNIQUE IDENTIFIER            0
LAST EDITED DATE                    0
TAXONOMIC ORDER                     0
CATEGORY                            0
TAXON CONCEPT ID                    0
COMMON NAME                         0
SCIENTIFIC NAME                     0
SUBSPECIES COMMON NAME        1354878
SUBSPECIES SCIENTIFIC NAME    1354878
EXOTIC CODE                   1330367
OBSERVATION COUNT                   0
BREEDING CODE                 1211588
BREEDING CATEGORY             1211588
BEHAVIOR CODE                 1211588
AGE/SEX                       1375384
COUNTRY                             0
COUNTRY CODE                        0
STATE                               0
STATE CODE                          0
COUNTY                              0
COUNTY CODE                         0
IBA CODE                      1181976
BCR CODE                        39202
USFWS CODE                    1350502
ATLAS BLOCK                    950579
LOCALITY                            0
LOCALITY ID                         0
LOCALITY TYPE                       0
LATITUDE                            0
LONGITUDE                           0
OBSERVATION DATE                    0
TIME OBSERVATIONS STARTED        1462
OBSERVER ID                         0
SAMPLING EVENT IDENTIFIER           0
PROTOCOL TYPE                       0
PROTOCOL CODE                       0
PROJECT CODE                        0
DURATION MINUTES                64936
EFFORT DISTANCE KM             389528
EFFORT AREA HA                1380435
NUMBER OBSERVERS                 1835
ALL SPECIES REPORTED                0
GROUP IDENTIFIER              1007299
HAS MEDIA                           0
APPROVED                            0
REVIEWED                            0
REASON                        1380924
TRIP COMMENTS                 1169108
SPECIES COMMENTS              1334467
Unnamed: 49                   1380924
dtype: int64

In [19]:
row_count = df.shape[0]
row_count

1380924

In [17]:
df.dropna(axis=1,
          thresh=(row_count*.9),
          inplace=True,
          )

In [18]:
df.shape

(1380924, 33)

In [21]:
df.columns

Index(['GLOBAL UNIQUE IDENTIFIER', 'LAST EDITED DATE', 'TAXONOMIC ORDER',
       'CATEGORY', 'TAXON CONCEPT ID', 'COMMON NAME', 'SCIENTIFIC NAME',
       'OBSERVATION COUNT', 'COUNTRY', 'COUNTRY CODE', 'STATE', 'STATE CODE',
       'COUNTY', 'COUNTY CODE', 'BCR CODE', 'LOCALITY', 'LOCALITY ID',
       'LOCALITY TYPE', 'LATITUDE', 'LONGITUDE', 'OBSERVATION DATE',
       'TIME OBSERVATIONS STARTED', 'OBSERVER ID', 'SAMPLING EVENT IDENTIFIER',
       'PROTOCOL TYPE', 'PROTOCOL CODE', 'PROJECT CODE', 'DURATION MINUTES',
       'NUMBER OBSERVERS', 'ALL SPECIES REPORTED', 'HAS MEDIA', 'APPROVED',
       'REVIEWED'],
      dtype='object')

In [22]:
df.dtypes

GLOBAL UNIQUE IDENTIFIER      object
LAST EDITED DATE              object
TAXONOMIC ORDER                int64
CATEGORY                      object
TAXON CONCEPT ID              object
COMMON NAME                   object
SCIENTIFIC NAME               object
OBSERVATION COUNT             object
COUNTRY                       object
COUNTRY CODE                  object
STATE                         object
STATE CODE                    object
COUNTY                        object
COUNTY CODE                   object
BCR CODE                     float64
LOCALITY                      object
LOCALITY ID                   object
LOCALITY TYPE                 object
LATITUDE                     float64
LONGITUDE                    float64
OBSERVATION DATE              object
TIME OBSERVATIONS STARTED     object
OBSERVER ID                   object
SAMPLING EVENT IDENTIFIER     object
PROTOCOL TYPE                 object
PROTOCOL CODE                 object
PROJECT CODE                  object
DURATION MINUTES             float64
NUMBER OBSERVERS             float64
ALL SPECIES REPORTED           int64
HAS MEDIA                      int64
APPROVED                       int64
REVIEWED                       int64
dtype: object

In [23]:
pd.to_numeric(df['OBSERVATION COUNT'],errors='coerce')

0          2.0
1          4.0
2          4.0
3          5.0
4          5.0
          ...
1380919    1.0
1380920    1.0
1380921    1.0
1380922    1.0
1380923    1.0
Name: OBSERVATION COUNT, Length: 1380924, dtype: float64

In [24]:
df['OBSERVATION COUNT'] = pd.to_numeric(df['OBSERVATION COUNT'],errors='coerce')

In [31]:
df['OBSERVATION COUNT'] = df['OBSERVATION COUNT'].fillna(1)

In [32]:
df['OBSERVATION COUNT'].isnull().sum()

0

In [33]:
df.isna().sum()

GLOBAL UNIQUE IDENTIFIER         0
LAST EDITED DATE                 0
TAXONOMIC ORDER                  0
CATEGORY                         0
TAXON CONCEPT ID                 0
COMMON NAME                      0
SCIENTIFIC NAME                  0
OBSERVATION COUNT                0
COUNTRY                          0
COUNTRY CODE                     0
STATE                            0
STATE CODE                       0
COUNTY                           0
COUNTY CODE                      0
BCR CODE                     39202
LOCALITY                         0
LOCALITY ID                      0
LOCALITY TYPE                    0
LATITUDE                         0
LONGITUDE                        0
OBSERVATION DATE                 0
TIME OBSERVATIONS STARTED     1462
OBSERVER ID                      0
SAMPLING EVENT IDENTIFIER        0
PROTOCOL TYPE                    0
PROTOCOL CODE                    0
PROJECT CODE                     0
DURATION MINUTES             64936
NUMBER OBSERVERS              1835
ALL SPECIES REPORTED             0
HAS MEDIA                        0
APPROVED                         0
REVIEWED                         0
dtype: int64

In [34]:
df.to_csv(r'C:\Users\ChaceHawkins\OneDrive - Human Coalition\Documents\Code learning\Portfolio projects\Birds\Spring_2023_data.csv')